[workspace]
resolver = "2"
members = ["projects/*"]
default-members = [
    "projects/zhihu-link",
]
exclude = [
    "projects/.DS_Store",
    "projects/zhihu-wolfram",
]

[profile.release]
lto = true
panic = "abort"
